# name
name: hello_world

# trigger
on:
- push

# one or more jobs
jobs:
    greetings:
        runs-on: ubuntu-latest
        steps:
        - id: s00
        # runs bash/zsh/cli tool
          run: echo "Current time in Github is $(date), GITHUB_OUTPUT is $(GITHUB_OUTPUT)"
        - id: s01
          run: echo "CURR_DATE = $(date)" >> $(GITHUB_OUTPUT)"
        - id: s02
          uses: mscoutermarsh/cowsays-action@master
          with:
            text: 'moo moo cow $${{steps.s01.outputs.CURR_DATE}}'
            color: 'red'
